//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoD2MP_w.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoD2MP_w.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gfx_d3d_mp_x86_s.dll.
        /// </summary>
        internal static string DllName {
            get {
                return ResourceManager.GetString("DllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoD2MP_s.exe.
        /// </summary>
        internal static string ExeName {
            get {
                return ResourceManager.GetString("ExeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon HighQuality {
            get {
                object obj = ResourceManager.GetObject("HighQuality", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls are not supported!.
        /// </summary>
        internal static string MsgMultipleCalls {
            get {
                return ResourceManager.GetString("MsgMultipleCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found!.
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __gfx_d3d_mp_x86.dll.
        /// </summary>
        internal static string NewDllName {
            get {
                return ResourceManager.GetString("NewDllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __CoD2MP.exe.
        /// </summary>
        internal static string NewExeName {
            get {
                return ResourceManager.GetString("NewExeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of Duty 2 Multiplayer.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
